-- ============================================================
-- ESTADO: aplicado parcialmente en
-- prisma/migrations/20260709090000_rls_and_missing_tables/migration.sql
-- ============================================================
-- Este archivo ya NO es solo referencia — ese migration.sql activa RLS de
-- verdad para: pages, page_versions, themes, domains, analytics_events.
-- Los repositorios de esos módulos (pages, themes) ya fueron refactorizados
-- para pasar por PrismaService.withWorkspace() en vez de usar el cliente
-- directo. Antes de esta refactorización, NINGÚN repositorio lo hacía
-- (ver docs/11-Auditoria-Produccion.md, hallazgo #2) — eso ya no es cierto
-- para estas cinco tablas.
--
-- LO QUE SIGUE PENDIENTE A PROPÓSITO: `roles` y `members` NO tienen RLS.
-- Razón: ListMyWorkspacesUseCase necesita listar TODOS los workspaces de
-- un usuario (member.findMany({ where: { userId } })) — es una query
-- legítimamente cross-tenant que no puede envolverse en un solo
-- withWorkspace(workspaceId, ...), porque en ese punto no hay un único
-- workspace en contexto. Activar RLS estricto ahí con el diseño actual
-- devolvería 0 filas para esa query en vez de protegerla.
--
-- Camino correcto para cerrar esto (siguiente incremento, no bloqueante
-- para el lanzamiento actual):
--   1. Añadir una segunda variable de sesión, `app.current_user_id`,
--      fijada en CADA request autenticado (no solo cuando hay un workspace
--      activo) — requiere envolver también las rutas "sin workspace" en
--      una transacción que la fije.
--   2. Política para `members`:
--        USING (
--          workspace_id = NULLIF(current_setting('app.current_workspace_id', true), '')::uuid
--          OR user_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
--        )
--      (la segunda condición te deja ver tus propias filas de membresía
--      en cualquier workspace, sin filtrar las de nadie más).
--   3. Política equivalente para `roles` en los casos donde se consulte
--      un rol de un workspace que no es el activo.
--   4. Solo entonces, mover esas dos tablas a una migración nueva.
--
-- Hoy, la única defensa para `members`/`roles` sigue siendo el
-- WorkspaceAccessGuard a nivel de aplicación (verificado: sí comprueba
-- membresía real contra la tabla en cada request a rutas de workspace).
-- Es una sola capa para esas dos tablas específicamente, no las dos que
-- el resto del esquema ya tiene.
